### ISSUE TITLE
Loss Graph Not Converging

### ISSUE THREAD

**Issue by tanh314** [rohitgirdhar/Deep-Q-Networks#1]
I am interesting in using your implementation, however I have a couple of questions about your loss graph:

1.  Why does your loss graph start and maintain at zero?  Shouldn't the random initialization of weights start loss at some non-zero value and converge (decrease) to some non-zero value?
2.  Why does your loss graph exhibit large spikes?  Does this behavior exhibit good model performance generally, but very poor performance on certain "outlier" states?

Thank you for any feedback you may provide.

**Comment by rohitgirdhar** [comment]
Thanks for your interest. I think this is common for deep RL problems, as there is no fixed dataset and it is created on the fly by epsilon-greedy search (playing the game, semi-optimally). Hence the loss value is not necessarily very meaningful, unlike a supervised classification setup.
